FROM eclipse-temurin:17-jdk

WORKDIR /app

COPY target/*.jar app.jar

# Copia o application.properties
COPY src/main/resources/application.properties /app/config/application.properties

# Expõe a porta 8080
EXPOSE 8080

# Roda a aplicação usando o .properties copiado
ENTRYPOINT ["java", "-jar", "app.jar", "--spring.config.location=file:/app/config/application.properties"]
